import { ArrowLeft, CalendarDays, MapPin } from "lucide-react";
import { Link, useParams } from "react-router";
import { Footer } from "../components/Footer";
import { Navigation } from "../components/Navigation";
import { getEventById } from "../data/events";

export function EventPage() {
  const { id } = useParams<{ id: string }>();
  const event = id ? getEventById(id) : undefined;
  if (!event) return <div className="min-h-screen bg-white"><Navigation /><main className="mx-auto max-w-[1440px] px-4 py-20 md:px-8"><h1 className="text-[48px] text-[var(--navy-deep)]" style={{ fontWeight: 750 }}>Event not found</h1><Link to="/events" className="mt-6 inline-block text-[#5a6eb4]">Return to events</Link></main><Footer /></div>;
  return <div className="min-h-screen bg-white"><Navigation /><main>
    <section className="mx-auto max-w-[1440px] px-4 py-4 md:px-8 md:py-6"><div className="relative min-h-[580px] overflow-hidden bg-[#17131f] md:min-h-[700px]"><img src={event.imageUrl} alt="" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/35 to-black/5" /><div className="absolute inset-x-0 bottom-0 max-w-[1050px] p-6 md:p-10 lg:p-12"><span className="text-[10px] font-bold uppercase tracking-[0.16em] text-white/70">{event.type}</span><h1 className="mt-4 text-[44px] leading-[0.98] text-white md:text-[68px]" style={{ fontWeight: 750 }}>{event.title}</h1><p className="mt-5 max-w-[780px] text-[16px] leading-[1.65] text-white/78 md:text-[18px]">{event.summary}</p><div className="mt-7 flex flex-wrap gap-6 text-[11px] font-semibold uppercase tracking-[0.11em] text-white/75"><span className="flex items-center gap-2"><CalendarDays size={15} />{event.date}</span><span className="flex items-center gap-2"><MapPin size={15} />{event.location}</span><span>{event.price}</span></div></div></div></section>
    <section className="mx-auto grid max-w-[1180px] gap-12 px-4 py-14 md:px-8 md:py-20 lg:grid-cols-[minmax(0,1fr)_300px]"><article><span className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#5a6eb4]">About the event</span><div className="mt-6 space-y-6">{event.description.map((paragraph) => <p key={paragraph} className="text-[18px] leading-[1.8] text-[var(--slate-dark)]">{paragraph}</p>)}</div><h2 className="mb-6 mt-14 text-[34px] text-[var(--navy-deep)]" style={{ fontWeight: 700 }}>Programme</h2><div className="border-t border-gray-200">{event.agenda.map((item) => <div key={`${item.time}-${item.title}`} className="grid gap-3 border-b border-gray-200 py-6 sm:grid-cols-[90px_1fr]"><span className="text-[12px] font-bold text-[#5a6eb4]">{item.time}</span><div><h3 className="text-[19px] text-[var(--navy-deep)]" style={{ fontWeight: 700 }}>{item.title}</h3><p className="mt-2 text-[14px] leading-[1.6] text-[var(--slate-dark)]">{item.description}</p></div></div>)}</div></article><aside className="space-y-6"><div className="border border-gray-200 bg-[#f7f8fc] p-7"><span className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#5a6eb4]">Attend</span><h2 className="mt-3 text-[25px] leading-[1.1] text-[var(--navy-deep)]" style={{ fontWeight: 700 }}>Join {event.title}</h2><p className="mt-4 text-[14px] leading-[1.6] text-[var(--slate-dark)]">{event.venue}<br />{event.date}</p><button type="button" className="mt-6 w-full bg-[#5a6eb4] px-5 py-4 text-[11px] font-bold uppercase tracking-[0.13em] text-white">Register now</button><h3 className="mt-8 border-t border-gray-200 pt-6 text-[10px] font-bold uppercase tracking-[0.14em] text-[var(--slate-medium)]">Speakers</h3>{event.speakers.map((speaker) => <div key={speaker.name} className="mt-4"><span className="block text-[13px] font-bold text-[var(--navy-deep)]">{speaker.name}</span><span className="mt-1 block text-[11px] leading-[1.4] text-[var(--slate-medium)]">{speaker.role}, {speaker.company}</span></div>)}</div></aside></section>
    <div className="mx-auto max-w-[1440px] px-4 py-8 md:px-8"><Link to="/events" className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.13em] text-[#5a6eb4]"><ArrowLeft size={15} />Back to events</Link></div>
  </main><Footer /></div>;
}
